apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryDataset
metadata:
  annotations:
    cnrm.cloud.google.com/delete-contents-on-destroy: "false"
    cnrm.cloud.google.com/project-id: zeya-explorer
  name: bigquerydatasetsample
spec:
  access:
    - role: OWNER
      specialGroup: projectOwners
    - role: WRITER
      specialGroup: projectWriters
  defaultTableExpirationMs: 3600000
  description: "BigQuery Dataset Sample"
  friendlyName: bigquerydataset-sample
  location: US
